title: Aria Pahlavan
#markdown: redcarpet
baseurl: ""
exclude: ['README.md']

# Build settings
markdown: kramdown
gems: [jekyll-assets, octopress-autoprefixer]
sass:
  style: compressed

permalink: pretty
collections:
  skills:
    layout: skill
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      type: skills
    values:
      layout: skill

theme: jekyll-theme-minimal